
# Map noise
SCALE = 0.04
OCTAVES = 4
PERSISTENCE = 0.5
LACUNARITY = 2.0
# Tree noise
SCALE_TREES = 0.06
OCTAVES_TREES = 4
PERSISTENCE_TREES = 0.5
LACUNARITY_TREES = 2.0
# Tree setting
TREE_DENSITY = 0.1
# Zoom
ZOOM_FACTOR = 0.05
ZOOM_MAX = 1.4
ZOOM_MIN = 0.2
# Config
CONFIG_PATH  = "data/config.json"